CREATE TABLE EMPLOYEE
(EID    INT  NOT NULL,
 FNAME  VARCHAR(15) NOT NULL,
 MINT   CHAR,  
 LNAME  VARCHAR(15) NOT NULL,
 SSN    INT  NOT NULL,
 DEP_ID INT, 
 PRIMARY KEY (EID),
 UNIQUE (SSN),
 foreign key (DEP_ID) references INTAKE_DEPARTMENT(DID)
);

