CREATE TABLE EMPLOYEE
(EID    INT  NOT NULL,
 FNAME  VARCHAR(15) NOT NULL,
 MINT   CHAR,
 LNAME  VARCHAR(15) NOT NULL,
 SSN    INT  NOT NULL,
 DEP_ID INT,
 PRIMARY KEY (EID),
 UNIQUE (SSN),
 FOREIGN KEY(DEP_ID) REFERENCES INTAKE_DEPARTMENT(DID)
);
