INSERT INTO DEPARTMENT
VALUES (1, 'INTAKE_DEPARTMENT');

INSERT INTO INTAKE_DEPARTMENT
VALUES(1, 'INTAKE_DEPARTMENT');

INSERT INTO EMPLOYEE
VALUES (1, 'Mary', 'A', 'Green', 123, 1);

INSERT INTO NURSE
VALUES (1, 'Mary', 'A', 'Green', 123);

INSERT INTO ASSESSMENT_NURSE
VALUES (1, 'Mary', 'A', 'Green', 123);

INSERT INTO PATIENT
VALUES (1, 'Stanley', 'B', 'Shepherd', '123', NULL, NULL, '456', '1996-06-11', 23);

INSERT INTO VISIT
VALUES (1, 100, '2019-12-12', 1, 1, 1, 200, '123', '456');

INSERT INITIAL_ASSESSMENT
VALUES (1, 1, 1);

INSERT INTO EMPLOYEE
VALUES (2, 'Carl', 'C', 'Smith', 999, 1);

INSERT SERVICE_PROVIDER
VALUES (2, 'Carl', 'C', 'Smith', 999);

INSERT TREATMENT
VALUES (1, 'b', 100, 'yes', 2, 999);

SELECT *
FROM VISIT;

SELECT *
FROM INITIAL_ASSESSMENT;

SELECT *
FROM TREATMENT;
