INSERT INTO DEPARTMENT
VALUES (1, 'INTAKE_DEPARTMENT');

INSERT INTO INTAKE_DEPARTMENT
VALUES(1, 'INTAKE_DEPARTMENT');

INSERT INTO EMPLOYEE
VALUES (1, 'Mary', 'A', 'Green', 123, 1);

INSERT INTO NURSE
VALUES (1, 'Mary', 'A', 'Green', 123);

INSERT INTO ASSESSMENT_NURSE
VALUES (1, 'Mary', 'A', 'Green', 123);

SELECT *
FROM ASSESSMENT_NURSE;
